language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - travis_retry composer install ${COMPOSER_FLAGS} --ignore-platform-reqs --no-interaction --prefer-dist
    - mkdir -p build/logs
    - composer run-script post-root-package-install
    - composer run-script post-create-project-cmd

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls